### ISSUE TITLE
Wrong episode download

### ISSUE THREAD

**Issue by phi-el** [carlosflorencio/laracasts-downloader#20] opened 2016-05-04 00:16 UTC
After first initial download, a video is downloaded into a wrong folder. So for example the series laravel-5-from-scratch contains a video(01-Initial Setup.mp4) which originally belongs to another series(I think its the build project flyer  with me series).

I was not able to solve the problem by simply deleting the wrong file and them redownload it.

I'm also not sure if this happens for other episodes too.

**Comment by carlosflorencio** [comment] 2016-05-04 11:01
Hi,

Sorry, i cannot reproduce your problem. Worked fine until now.

Can you try find the problem?

**Comment by carlosflorencio** [comment] 2016-05-04 11:12
Found the problem, is a laracasts problem.

The download of the first episode of laravel-5-from-scratch is the wrong file!

https://laracasts.com/series/laravel-5-from-scratch/episodes/1

Maybe you want to tell jeffrey about that.

Closing!

**Closed as completed by carlosflorencio** 2016-05-04 11:12 UTC
